[phases.setup]
nixPkgs = [
    "...",
    "cairo",
    "pango",
    "gobject-introspection",
    "glib",
    "libffi",
    "pkg-config",
    "fontconfig",
    "freetype",
    "harfbuzz"
]
nixLibs = [
    "...",
    "cairo",
    "pango",
    "gobject-introspection",
    "glib",
    "libffi",
    "fontconfig",
    "freetype",
    "harfbuzz"
]
